### PR TITLE
viewer: Add EnkiPlaygroundServer.

### PR DESCRIPTION
**Pull request by mthl**
This is a first step in using Dashel stream library for networking.

### CODE REVIEW

**Comment by nicpalard** [comment]
+1

**Comment by nicpalard** [comment]
#+1

**Comment by nicpalard** [comment]
# +1

**Comment by mthl** [comment]
I have created `PlaygroundServer.cpp` which runs a minimal world.

@sebpouteau Please check if that suits you.

**Comment by sebpouteau** [comment]
it's ok.

**Comment by mthl** [comment]
Applied as e233d050ec18793d97778f365416481dbedcfe62

**Pull request closed without merging**
